### ISSUE TITLE
Support of Nuxt 3

### ISSUE THREAD

**Issue by kjanusz** [ionos-deploy-now/hello-nuxt#5]
When will you support the nuxt 3 version? Could you publish an hello-nuxt example for nuxt 3?

**Comment by philipphoberg** [comment]
Hey @kjanusz,
if you are using Nuxt3 as a static (SSG) Framework ([More Info On Static Nuxt 3 Deployment](https://v3.nuxtjs.org/guide/deploy/static-hosting/)), the following configuration should work for you. It works flawlessly with my Deploy-Now-Nuxt3 Project. 

There are 2 ways to make it work 
1. On intial setup
   - Do the usual Deploy-Now setup choosing your repo and the Nuxt-Framework (which still is Nuxt2)
   - The deployment commands will be shown to you
   - add `--shamefully-hoist `to pnpm (like so `pnpm install --shamefully-hoist`)
   - Remove pnpm run build (it is not needed for [Nuxt3-Static-Mode](https://v3.nuxtjs.org/guide/deploy/static-hosting/))
   - change the output file location from `.dist` to  `./.output/public`
2. If you already have an `.github/workflows/.deploy-now.yml` created using the Nuxt2 preset
  - The deployment will fail, but do not worry!
  - Edit your `.github/workflows/.deploy-now.yml` `-name build Node Assets ` section to run the same commands as above
     - it shoud look like this:
        ```
        - name: Build Node assets
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        env:
          CI: true
          SITE_URL: ${{ steps.project.outputs.site-url }}
        run: |
          npm install --global pnpm
          pnpm install --shamefully-hoist
          pnpm generate
        ```
  - Edit your `.github/workflows/.deploy-now.yml` `-name Deploy to IONOS ` section to the abovementioned dist-folder
       - it shoud look like this:
        ```
        - name: Deploy to IONOS
          if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
          uses: ionos-deploy-now/deploy-to-ionos-action@v1
          with:
            project: ${{ secrets.IONOS_PROJECT_ID }}
            branch-id: ${{ steps.project.outputs.branch-id }}
            service-host: api-eu.ionos.space
            api-key: ${{ secrets.IONOS_API_KEY }}
            dist-folder: ./.output/public
        ```

**Comment by kjanusz** [comment]
Hey @philipphoberg , thank you for the information, will try it soon. 

For the time, i helped myself with the following changes in nuxt 2 deploy-now.yml:

```yml
- name: Build Node assets
  run: 
    npm ci
    npm run generate
..
- name: Deploy to IONOS
  with:
    dist-folder: .output/public
```

Here is a complete version:

```yml
# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: Deploy Now

on:
  - push
  - workflow_dispatch

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space

      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: v16.x

      - name: Build Node assets
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        env:
          CI: true
          SITE_URL: ${{ steps.project.outputs.site-url }}
        run: |
          npm ci
          npm run generate

      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          project: ${{ secrets.IONOS_PROJECT_ID }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          dist-folder: .output/public
```

I like your variant because I can switch to pnpm 😄
